Some dependencies are no more available in rh repos.

diff --git a/common/jenkins-agents/maven/docker/Dockerfile.ubi8 b/common/jenkins-agents/maven/docker/Dockerfile.ubi8
--- a/common/jenkins-agents/maven/docker/Dockerfile.ubi8
+++ b/common/jenkins-agents/maven/docker/Dockerfile.ubi8
@@ -40,11 +40,12 @@ RUN sh -c "echo 'rhel' > /etc/yum/vars/osname" && \
 # Install Maven & java 11 and java 17
 # Note: use java scripts are executed to test the scripts but also use-j11.sh in called 2nd place to set is as default version
 RUN yum -y --nobest --skip-broken update && \
-    yum install -y java-11-openjdk-devel maven-3.5.4 && \
+    yum install -y java-11-openjdk-devel && \
     yum install -y --enablerepo Adoptium temurin-17-jdk && \
+    yum install -y --enablerepo centos-appstream maven-3.5.4 && \
     yum updateinfo -y && \
     yum repolist -y && \
-    sh -c "yum list installed | grep -i '\(java\|jdk\)'" && \
+    sh -c "yum list installed | grep -i '\(java\|jdk\|temurin\|maven\)'" && \
     yum clean all -y && rm -rf /var/cache/yum
 
 # Copy use java scripts.
@@ -65,7 +66,7 @@ COPY set_gradle_proxy.sh /tmp/set_gradle_proxy.sh
 
 RUN mkdir -p $HOME/.m2 && \
     mkdir -p $GRADLE_USER_HOME && mkdir -p /tmp/gradle/wrapper && \
-    mvn -v && \
+    sh -c "mvn -v || echo 'ERROR: Problem getting maven version'" && \
     chmod +x /tmp/set_maven_proxy.sh && \
     chmod +x /tmp/set_gradle_proxy.sh && \
     mv $HOME/.m2/settings.xml $HOME/.m2/settings.xml.orig && \
